### ISSUE TITLE
AppImage is missing libsecret-1.so.0

### ISSUE THREAD

**Issue by probonopd** [gongchat/gong#1]
Does not run on Ubuntu 18.04, `libsecret-1.so.0` needs to be bundled in the AppImage:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8419/resources/app.asar/node_modules/keytar/lib/keytar.js:1:107)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8419/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
```

References:
* https://github.com/AppImage/appimage.github.io/pull/1380
* https://github.com/electron-userland/electron-builder/issues/2597
* https://github.com/electron-userland/electron-builder/issues/3693

Possibly `extraFiles` can be used in the meantime: https://github.com/electron-userland/electron-builder/issues/2732

**Comment by david-j-lee** [comment]
Hi @probonopd, I was able to get the build working. Going to close this issue, thanks!

**Comment by probonopd** [comment]
Thanks @david-j-lee. Please ping me once a new version containing the fix is available for download, so that I can re-run the test. Thank you.

**Comment by david-j-lee** [comment]
@probonopd oops, I thought this issue was in regards to the Tavis build failing, should have not assumed my bad. Give this version a try https://github.com/gongchat/gong/releases/tag/v0.1.2 if it is still causing problems please let me know so I can reopen this issue.
